name: Deploy Node.js Backend to Droplet

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            echo '📦 Pulling latest code...'
            git pull origin release
            echo '📦 Installing dependencies...'
            npm install --production
            echo '🚀 Restarting PM2...'
            pm2 reload all 
            echo '🔁 Reloading OpenResty...'
            sudo /usr/local/openresty/bin/openresty -s reload
