name: Deploy Node.js Backend to Droplet

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            set -e
            cd ${{ secrets.REMOTE_PATH }}

            echo '📦 Pulling latest code...'
            git pull origin release

            echo '📦 Installing dependencies...'
            npm install --production

            echo '🚀 Restarting PM2...'

              pm2 reload all


            echo '✅ PM2 status:'
            pm2 list

            echo '🔁 Reloading OpenResty...'
            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S /usr/local/openresty/bin/openresty -s reload

            echo '✅ Deployment completed successfully!'
